use sciratedb
go

create table tElibraryAuthors (
    id int identity(1,1) constraint PK_tElibraryAuthors primary key,
    elibraryAuthorId int NOT NULL,
    lnkPersonnel int,
    lastName nvarchar(255),
    firstName nvarchar(255),
    secondName nvarchar(255),
    city nvarchar(255),
    numOfLibraryItems int,
    numofItemsFull int,
    libraryCited int,
    citedRefs int,
    citingPubl int,
    maxItemCited int,
    publCited int,
    publCitedPrc float(5),
    avgCited float(5),
    numOfCoreItems int,
    numOfCoreItemsPrc float(5),
    coreCited int,
    hirsch int,
    hirschs int,
    hirscha int,
    hirschCore int,
    hirschFull int,
    firstPublYear int,
    selfCited int,
    selfCitedPrc float(5),
    coauthorCited  int,
    coauthorsNum int,
    publForeign int,
    publRussian int,
    publVAK int,
    publTranslated int,
    publIF int,
    citForeign int,
    citRussian int,
    citVAK int,
    citTranslated int,
    citIF int,
    avgPublIF float(5),
    avgCitIF float(5),
    publ5 int,
    citPubl5 int,
    cit5 int,
    FOREIGN KEY (lnkPersonnel) REFERENCES tPersonnel(id)
)

